Feature/dss12 sc 181423 multi sheet excel export apply a formatting
dataiku/dss-plugin-multisheet-excel-export pull request #6
Opened 2024-05-22 16:01 UTC by Ellana42

Added a styled header to the exported spreadsheets - similar to the style of DSS native excel export. The columns are also auto-sized to fit the header text.

2024-05-27 07:47 UTC, Ellana42 commented
[sc-181422]

2024-05-27 15:52 UTC, MayeulRousselet requested changes
LGTM and tested, very solid work!
Only a small comment todo 
Tested:
- On a empty dataset: the same error as in the previous version is raised
- 2 datasets as input: 2 sheets are generated
- with an empty colum: header is added
- With 1M lines

2024-05-27 15:58 UTC, MayeulRousselet approved these changes

2024-05-27 16:22 UTC, alexbourret approved these changes
👍 All good !

2024-05-28 08:01 UTC, merged

2024-06-03 10:18 UTC, Ellana42 commented on python-lib/xlsx_writer.py
> +        logger.warn(f"No header row for worksheet {worksheet}. Styling skipped.")
yes, I checked